language: cpp

branches:
  only:
    - master

matrix:
  include:
    - os: linux
      dist: xenial
      compiler:
        - clang

    - os: linux
      dist: xenial
      compiler:
        - gcc

#    - os: osx
#      osx_image: xcode10.1
#
#    - os: osx
#      osx_image: xcode7.0

script: cmake -H. -B_builds/Debug -DCMAKE_BUILD_TYPE=Debug && cmake --build _builds/Debug